### ISSUE TITLE
Ask About Edge with Fast Brief NH

### ISSUE THREAD

**Issue by duyouzhi** [sglbl/Stereo-Correspondence-For-Disparity#1]
Hello, thank you very much for sharing. Your program has greatly benefited me. However, when I run 'Edge with Fast Brief NH' with my own image, only 'Image of Matches' will be displayed, instead of' My disparity map 'as shown in' ORB 'and' SIFT '. Why? thank you.

**Comment by sglbl** [comment]
There was a redundant statement, I removed and fixed it. You can check. Also, "Image of Matches" shows grayscale image matches.
